name: mingo_shop
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.2
  flutter_snake_navigationbar: ^0.6.1
  badges: ^2.0.2
  http: ^1.1.0
  flutter_easyloading: ^3.0.5
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  carousel_slider:
  intl: ^0.18.1

  #local db
  hive: ^2.2.3
  hive_flutter: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
